[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[dev]
  command = "sanity start"
  port = 8888
  targetPort = 3333
  framework = "#custom"
  publish = "dist"

  [functions]
    directory = "netlify/functions"